bundler_args: --without development
before_script: ./bin/ci/before_build.sh
script: "bundle exec rspec"
rvm:
  - ruby-head
  - "2.6.0"
  - "2.5.1"
  - "2.4.2"
  - "2.3.5"
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
