bundler_args: --without development
script: "bundle exec rspec --color --format documentation spec"
rvm:
  - "2.3.0"
  - "2.2.2"  
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: 1.8.7
