bundler_args: --without development
before_script: ./bin/ci/before_build.sh
script: "bundle exec rspec"
rvm:
  - "2.4"
  - "2.3.3"
  - "2.2"
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
