dist: bionic
language: ruby
bundler_args: --without development
cache: bundler
before_install:
  - gem install bundler
before_script:
  - "./bin/ci/install_on_debian.sh"
  - until sudo lsof -i:5672; do echo "Waiting for RabbitMQ to start..."; sleep 1; done
  - "./bin/ci/before_build.sh"
script: "bundle exec rspec"
rvm:
  - ruby-head
  - "2.7.1"
  - "2.6.6"
  - "2.5.8"
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
